name:                cses-fi
version:             0.1.0.0
github:              "h9h/cses-fi"
license:             BSD3
author:              "Michael Heinke"
maintainer:          "haskell.projects@h9h.de"
copyright:           "Copyright (c) 2021 Michael Heinke"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/h9h/cses-fi#readme>

dependencies:
- base >= 4.7 && < 5
- protolude

library:
  source-dirs: src

executables:
  cses-fi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cses-fi
    - containers
    - mtl
    - bytestring

tests:
  cses-fi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cses-fi
